### ISSUE TITLE
Use R package for JSON Creation

### ISSUE THREAD

**Issue by zachcp** [zachcp/phyloTreeWidget#1]
Right now JSON creation is happening by piping into python and reading the JSON back into R before passing it to the HTMLWidgets.

I think that using the `data.tree` package I should be able to iterate through the `data.tree` and build up the JSON as a list of lists, exactly analogous to the current code in python which iterates through the tree.

**Comment by zachcp** [comment]
now implemented but the tree --> data.tree --> list of lists is about 10x slower than piping through python for large trees. I will need look into a streamlined serializer - especially one that can respect the output of ape::ladderize

**Comment by zdk123** [comment]
Hope you don't mind that I've been watching this repo!... I meant to warn
you that data.tree is slow. A possible option is implement our own tree in
C++ and use Rcpp for much faster performance. Data piping is still fast.

**Comment by zachcp** [comment]
I don't mind at all! I guess you are getting tired of vacation :). 

I agree about C+/Rcpp but its a relatively low priority since we've got a working alternative. Could be a good project for some "spare cycles" though.

**Comment by zachcp** [comment]
addressed in #8
